In [2]:
import os
import requests
from pathlib import Path

# -------------------------------------------------
# 1. Definir onde fica a pasta de saida
# -------------------------------------------------
current_dir = Path.cwd()
parent_dir = current_dir.parent
data_folder = parent_dir/'data'

# -------------------------------------------------
# 2. Cria a pasta 'data' se ela não existir
# -------------------------------------------------

data_folder.mkdir(parents=True, exist_ok=True)

# -------------------------------------------------
# 3. Definir a URL e os headers (já estão ok)
# -------------------------------------------------
url = "https://dados.agricultura.gov.br/dataset/6c913699-e82e-4da3-a0a1-fb6c431e367f/resource/d30b30d7-e256-484e-9ab8-cd40974e1238/download/agrofitprodutosformulados.csv"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# -------------------------------------------------
# 4. Fazer o download
# -------------------------------------------------

response = requests.get(url, headers=headers, stream=True, timeout=30)

# -------------------------------------------------
# 5. Salvar o CSV na pasta data (modo “streaming” para arquivos grandes)
# -------------------------------------------------

csv_path = data_folder/"agrofitprodutosformulados.csv"


with open(csv_path, "wb") as f:
    for chunk in response.iter_content(chunk_size=8192):   # leitura por blocos
        f.write(chunk)

In [3]:
import pandas as pd
from IPython.display import display, Markdown
from datetime import datetime


# Importando arquivo csv e convertendo tipos
df = pd.read_csv(csv_path, sep=';', engine='pyarrow')
df = df.convert_dtypes()

# Limpando os nomes das empresas para facilitar a leitura
df['TITULAR'] = df['TITULAR_DE_REGISTRO'].str.split().str[0]

---

# Análise do banco de dados do Agrofit

In [4]:
data = datetime.now().strftime("%d/%m/%Y")
display(Markdown(f'''### Dados obtidos no dia **{data}**\n\n
#### Produzido e analisado por **[Luan Vinícius Silva Dias](https://www.linkedin.com/in/luan-vinicius-silva-dias/)**.
'''))

### Dados obtidos no dia **01/02/2026**


#### Produzido e analisado por **[Luan Vinícius Silva Dias](https://www.linkedin.com/in/luan-vinicius-silva-dias/)**.

---

In [5]:
df.columns

Index(['NR_REGISTRO', 'MARCA_COMERCIAL', 'FORMULACAO', 'INGREDIENTE_ATIVO',
       'TITULAR_DE_REGISTRO', 'CLASSE', 'MODO_DE_ACAO', 'CULTURA',
       'PRAGA_NOME_CIENTIFICO', 'PRAGA_NOME_COMUM', 'EMPRESA_PAIS_TIPO',
       'CLASSE_TOXICOLOGICA', 'CLASSE_AMBIENTAL', 'ORGANICOS', 'SITUACAO',
       'TITULAR'],
      dtype='object')


## Visão geral do mercado/concentração

### Quantas empresas distintas existem no sistema?

In [6]:
# Criando um dataframe sem duplicatas de produtos com os nomes das empresas detentoras do registro
produtos_df = df[['NR_REGISTRO', 'TITULAR']].drop_duplicates(subset=['NR_REGISTRO'])

# Retornando o número de registros únicos dos titulares
empr = produtos_df['TITULAR'].nunique()
empr

308

In [7]:


display(Markdown(f'''\n
Como podemos ver, são **{empr}** empresas com CNPJ distintos inscritos no banco de dados do Agrofit.\n\n

Vale ressaltar que, algumas poucas empresas atuam sob diferentes inscrições.  

---\n'''))

Como podemos ver, são **308** empresas com CNPJ distintos inscritos no banco de dados do Agrofit.



Vale ressaltar que, algumas poucas empresas atuam sob diferentes inscrições.

---

### Top 10 empresas com mais produtos registrados

In [8]:
# Ordenar as 10 empresas com mais produtos registrados
produtos_df['TITULAR'].value_counts().head(10)

TITULAR
Syngenta    250
Adama       176
UPL         171
Nortox      168
Rainbow     160
Sumitomo    152
CTVA        144
Basf        118
FMC         108
Bayer        99
Name: count, dtype: int64

In [9]:
# Puxando a colocação da Nortox
colocNortox = produtos_df['TITULAR'].value_counts().index.get_loc('Nortox') + 1

# Puxando quantos produtos a Nortox tem
prodNortox = produtos_df['TITULAR'].value_counts().loc['Nortox']

display(Markdown(f'''\n

Acima, podemos ver as empresas e a quantidade de produtos registrados por cada uma em ordem decrescente.\n\n

Note que, dentre as empresas listada, **apenas 1** delas é genuinamente brasileira: a Nortox S.A., ocupando a {colocNortox}ª colocação com {prodNortox} produtos registrados.\n\n

---'''))

Acima, podemos ver as empresas e a quantidade de produtos registrados por cada uma em ordem decrescente.



Note que, dentre as empresas listada, **apenas 1** delas é genuinamente brasileira: a Nortox S.A., ocupando a 4ª colocação com 168 produtos registrados.



---

### Porcentagem de participação das top 10 empresas

In [10]:
# Porcentagem arredondada do número total de produtos das top 10 empresas comparadas ao total de produtos
porc_prod = round(produtos_df['TITULAR'].value_counts().head(10).sum() / produtos_df['NR_REGISTRO'].value_counts().sum() * 100, 2)

# Contagem de quantos produtos as top 10 empresas têm no cadastro
tot_prod_top10 = produtos_df['TITULAR'].value_counts().head(10).sum()

# Contagem total de todos os produtos
tot_prod = produtos_df['NR_REGISTRO'].value_counts().sum()

display(Markdown(f'''\n

Se formos contar a participação que as top 10 empresas têm sob o mercado nacional, elas juntas somam {porc_prod}% do mercado, ou ainda, {tot_prod_top10} produtos dos {tot_prod}.\n\n

---'''))

Se formos contar a participação que as top 10 empresas têm sob o mercado nacional, elas juntas somam 36.54% do mercado, ou ainda, 1546 produtos dos 4231.



---

### Quantos produtos cada empresa tem por classe das quatro grandes classes (herbicida, fungicida, inseticida e biológico)?

In [11]:
# Seleciona colunas relevantes e remove duplicatas de produtos
classes_df = df[['NR_REGISTRO', 'TITULAR', 'CLASSE']].drop_duplicates(subset=['NR_REGISTRO'])

# Cria colunas booleanas para as 4 principais classes
classes_df['HERBICIDA'] = classes_df['CLASSE'].str.contains('Herbicida', case=False, na=False)
classes_df['FUNGICIDA'] = classes_df['CLASSE'].str.contains('Fungicida', case=False, na=False)
classes_df['INSETICIDA'] = classes_df['CLASSE'].str.contains('Inseticida', case=False, na=False)
classes_df['(MICRO)BIOLÓGICO'] = classes_df['CLASSE'].str.contains('Biológico', case=False, na=False)

# Agrupa por empresa e soma a quantidade de produtos por classe
classes = classes_df.groupby('TITULAR', observed=True)[['HERBICIDA', 'FUNGICIDA', 'INSETICIDA', '(MICRO)BIOLÓGICO']].sum()

# Adiciona coluna de total para facilitar ordenação
classes['TOTAL'] = classes.sum(axis=1)

# Ordena pelas empresas com mais produtos e exibe as top 10
classes = classes.nlargest(n=10, columns='TOTAL')

classes

          HERBICIDA  FUNGICIDA  INSETICIDA  (MICRO)BIOLÓGICO  TOTAL
TITULAR
Syngenta         48        115          85                 7    255
Adama            88         43          36                 2    169
Nortox           84         38          43                 0    165
UPL              77         50          32                 3    162
Rainbow         114         27          17                 0    158
Sumitomo         58         23          53                10    144
CTVA             77         28          30                 0    135
Basf             30         53          29                 5    117
FMC              31         17          50                13    111
Bayer            20         41          31                 2     94

In [12]:
# Contagem de quais empresas tem mais de 70 herbicidas
herb = (classes['HERBICIDA'].head(10) >= 70).sum()

display(Markdown(f'''\n

Como podemos ver acima, a participação dos grandes players no mercado de (micro)biológicos ainda é irrisória frente aos produtos químicos.

Apesar disso, podemos ver a Syngenta ocupando o posto de primeira colocada em número de fungicidas e inseticidas registrados, tendo próximo do dobro de produtos quando comparado às demais empresas.

Quando olhamos para os herbicidas, o mercado é mais competitivo, com **{herb} de 10** tendo mais 70 produtos registrados, com a chinesa Rainbow encabeçando a lista.\n\n

---'''))

Como podemos ver acima, a participação dos grandes players no mercado de (micro)biológicos ainda é irrisória frente aos produtos químicos.

Apesar disso, podemos ver a Syngenta ocupando o posto de primeira colocada em número de fungicidas e inseticidas registrados, tendo próximo do dobro de produtos quando comparado às demais empresas.

Quando olhamos para os herbicidas, o mercado é mais competitivo, com **5 de 10** tendo mais 70 produtos registrados, com a chinesa Rainbow encabeçando a lista.



---

## Ingredientes ativos mais usados

**Ingredientes ativos** são as substâncias principais presentes nos agroquímicos responsáveis pela ação sobre organismos-alvo, como pragas, doenças e plantas daninhas. Eles são o componente essencial da formulação e determinam o modo de ação, eficácia e toxicidade do produto. Exemplos comuns incluem **glifosato** (herbicida), **2,4-D** (herbicida), **clorotalonil** (fungicida), **fipronil** (inseticida) e **clorpirifós** (inseticida).  

Esses ingredientes são combinados com **ingredientes inertes** (como solventes ou dispersantes) para melhorar a aplicação, estabilidade e eficiência do produto. A legislação brasileira exige que o ingrediente ativo seja claramente identificado no rótulo, pois é ele que define o risco à saúde humana e ao meio ambiente.

---

### Quais são os 10 ingredientes ativos mais frequentes nos produtos formulados?

In [13]:
import re

# 1. Seleciona e remove duplicatas de registro
ingredientes_df = df[['NR_REGISTRO', 'INGREDIENTE_ATIVO']].drop_duplicates(subset='NR_REGISTRO')

# 2. Separa por '+' (usando apenas '+' garante que pegue mesmo se o espaçamento variar)
ingredientes_df['INGREDIENTE_ATIVO'] = ingredientes_df['INGREDIENTE_ATIVO'].str.split('+')
ingredientes_df = ingredientes_df.explode('INGREDIENTE_ATIVO')

# 3. CRIA UMA NOVA COLUNA LIMPA (AQUI ESTÁ A CORREÇÃO)
# Padroniza para Texto Título e remove espaços nas pontas
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_ATIVO'].str.strip().str.title()

# Remove concentrações entre parênteses: "(480 g/L)"
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_LIMPO'].str.replace(r'\s*\(.*', '', regex=True)

# Remove isolados após vírgula, mas SALVA o 2,4-D (não remove se tiver número depois da vírgula)
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_LIMPO'].str.replace(r',(?!\d).*', '', regex=True)

# Remove variações de "Sal de..." ou "Éster"
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_LIMPO'].str.replace(r'\s*-?\s*\bSal\b.*', '', regex=True, flags=re.IGNORECASE)
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_LIMPO'].str.replace(r'\s*-?\s*\bÉster\b.*', '', regex=True, flags=re.IGNORECASE)

# Tira espaços finais
ingredientes_df['INGREDIENTE_LIMPO'] = ingredientes_df['INGREDIENTE_LIMPO'].str.strip()

# 4. Conta usando a coluna LIMPA
ingr = ingredientes_df['INGREDIENTE_LIMPO'].value_counts().head(10)
ingr

INGREDIENTE_LIMPO
Glifosato                 186
Beauveria Bassiana        157
Metarhizium Anisopliae    139
Trichoderma Harzianum     108
Mancozebe                 105
Clorotalonil              101
Azoxistrobina              98
Tebuconazol                89
Atrazina                   87
Picloram                   78
Name: count, dtype: int64

In [14]:
filt_gli = ingr.index.str.contains('glifosato', case=False)
gli = ingr.iloc[filt_gli].sum()

filt_glu = ingr.index.str.contains('glufosinato', case=False)
glu = ingr.iloc[filt_glu].sum()

display(Markdown(f'''\n

Os dados mostram que o **Glifosato** continua sendo o primeiro colocado absoluto dos defensivos no Brasil, com **{gli}** produtos, servindo como a principal ferramenta para limpeza de terreno na maioria das plantações.

A grande revolução, porém, está nos **Biológicos**: três dos quatro ingredientes mais registrados são fungos naturais (**Beauveria, Metarhizium e Trichoderma**), provando que a indústria aposta pesado em soluções mais sustentáveis que servem para diversas culturas.

Por fim, vemos a força dos fungicidas protetores (**Mancozebe** e **Clorotalonil**), que funcionam como um reforço para a proteção das lavouras.

---'''))

Os dados mostram que o **Glifosato** continua sendo o primeiro colocado absoluto dos defensivos no Brasil, com **186** produtos, servindo como a principal ferramenta para limpeza de terreno na maioria das plantações.

A grande revolução, porém, está nos **Biológicos**: três dos quatro ingredientes mais registrados são fungos naturais (**Beauveria, Metarhizium e Trichoderma**), provando que a indústria aposta pesado em soluções mais sustentáveis que servem para diversas culturas.

Por fim, vemos a força dos fungicidas protetores (**Mancozebe** e **Clorotalonil**), que funcionam como um reforço para a proteção das lavouras.

---

### Quantos % dos produtos são alguma formulação de Glifosato?

In [15]:
# Gera uma variável "glifosato", onde é um agregado de todos os produtos que tenham alguma fórmula desse ativo
glifosato = ingredientes_df['INGREDIENTE_ATIVO'].str.contains('glifosato', case=False, na=False)

# Retorna a porcentagem de produtos que são glifosato dentro do banco de dados
porc_gli = round(ingredientes_df.value_counts(glifosato, normalize=True) * 100, 2)
porc_gli

INGREDIENTE_ATIVO
False    96.56
True      3.44
Name: proportion, dtype: float64

In [16]:
gli_porc = porc_gli.iloc[1]

display(Markdown(f'''\n

Diante da enorme expressividade do **glifosato**, uma análise curiosa revela que **{gli_porc}%** dos produtos cadastrados são alguma espécie de glifosato.\n\n

---'''))

Diante da enorme expressividade do **glifosato**, uma análise curiosa revela que **3.44%** dos produtos cadastrados são alguma espécie de glifosato.



---

### Quais ingredientes ativos podem ser utilizados no maior número de culturas diferentes?

In [17]:
# Gera uma variável "culturas_ingr_df", que é o agrupamento dos valores únicos dos ingredientes ativos por cultura
culturas_ingr_df = df.groupby('INGREDIENTE_ATIVO', observed=True)['CULTURA'].nunique()

# Retorna os 10 ingredientes ativos com mais ocorrência dentro das culturas
culturas_ingr_df.nlargest(10)

INGREDIENTE_ATIVO
Azoxistrobina (estrobilurina) (200 g/L) + difenoconazol (triazol) (125 g/L)          124
difenoconazol (triazol) (250 g/L)                                                    120
fluxapiroxade (carboxamida) (167 g/L) + piraclostrobina (estrobilurina) (333 g/L)    100
lambda-cialotrina (piretróide) (250 g/L)                                              91
glifosato-sal de isopropilamina (glicina substituída) (480 g/L)                       88
ciprodinil (anilinopirimidina) (750 g/kg)                                             87
diafentiurom (feniltiouréia) (500 g/L)                                                86
Azoxistrobina (estrobilurina) (500 g/kg)                                              85
Swinglea glutinosa (Terpenos), Extrato de (Derivado vegetal) (868.4 g/L)              83
azadiractina (Tetranortriterpenóide) (12 g/L)                                         83
Name: CULTURA, dtype: int64

---

Quando olhamos para os ingredientes ativos mais utilizados no espectro das culturas, vemos uma predominância dos fungicidas, ocupando os 3 primeiros lugares no ranking, com pelo menos 100 culturas em cada.
Isso se deve ao amplo espectro de ação dos mesmos, sendo capaz de atuar nas mais diversas culturas cultivadas.

A lambda-cialotrina (inseticida) e o glifosato - sal de isopropilamina (herbicida) compõem o restante dos top 5 ingredientes ativos mais versáteis.

Há destaque para o top 9 e 10, onde ambos são óleos de origem vegetal (um fungicida/bactericida e outro inseticida).

---

## Classe de uso

Os **agroquímicos** são classificados de acordo com o tipo de praga ou organismo que atuam, sendo os principais tipos de ação:

- **Inseticidas**: Combatem insetos e pragas que atacam as plantas, como pulgões, lagartas e percevejos.
- **Fungicidas**: Controlam fungos causadores de doenças em culturas, como mofo, ferrugem e manchas foliares.
- **Herbicidas**: Destinam-se ao controle de plantas daninhas, eliminando ou inibindo seu crescimento.
- **Acaricidas**: Atuam contra ácaros, pequenos artrópodes que danificam folhas e frutos.
- **Nematicidas**: Combatem nematoides (vermes parasitas do solo) que prejudicam as raízes das plantas.
- **Rodenticidas**: Eliminam roedores como ratos e toupeiras que danificam lavouras.
- **Bactericidas**: Inibem ou matam bactérias que causam infecções em plantas.
- **Reguladores de crescimento**: Ajustam o desenvolvimento vegetal, como acelerar o amadurecimento ou controlar o crescimento de plantas.

Essa classificação é baseada na **natureza do organismo-alvo**, sendo essencial para o uso correto e eficaz dos produtos na agricultura.

Os **produtos biológicos** são produtos derivados de organismos vivos, utilizados no controle de pragas e doenças de forma mais sustentável. Diferentemente dos agroquímicos, atuam com maior seletividade e menor impacto ambiental. 

### Principais tipos de ação dos produtos biológicos:

1. **Inimigos naturais**  
   Insetos predadores ou parasitoides (como *Trichogramma* spp.) que controlam populações de pragas, como lagartas e pulgões. 

2. **Micro-organismos**  
   Bactérias (ex: *Bacillus thuringiensis*), fungos (ex: *Beauveria bassiana*) e vírus que infectam e eliminam insetos-praga. 

3. **Antagonistas microbianos**  
   Micro-organismos que competem ou inibem patógenos do solo, como fungos causadores de murchas. 


Esses produtos são essenciais na **Agricultura Orgânica** e no **Manejo Integrado de Pragas (MIP)**, promovendo equilíbrio ecológico e reduzindo a dependência de produtos sintéticos.

---

### Distribuição de produtos por classe de uso

#### Selecionando as 10 classes mais repetidas (sem desmembrar)

In [18]:
# Seleciona colunas relevantes e remove duplicatas de produtos
distribuicao_df = df[['NR_REGISTRO', 'CLASSE']].drop_duplicates('NR_REGISTRO')

# Retorna a proporção em que as classes de ativos não estão separadas, incluindo combinações de classes
classe_nao_sep = round(distribuicao_df.value_counts(subset='CLASSE', normalize=True).head(10) * 100, 2)
classe_nao_sep

CLASSE
Herbicida                                             33.54
Fungicida                                             17.63
Inseticida                                            15.24
Inseticida Microbiológico                              7.80
Acaricida/Inseticida                                   3.73
Fungicida microbiológico                               3.50
Regulador de Crescimento                               2.58
Nematicida Microbiológico                              2.36
Agente Biológico de Controle                           2.20
Acaricida Microbiológico/Inseticida Microbiológico     1.80
Name: proportion, dtype: float64

#### Selecionando as 10 classes mais repetidas (desmembrando)

In [19]:
# Cria uma coluna CLASSE onde as combinações de ativos são separadas
distribuicao_df['CLASSE'] = distribuicao_df['CLASSE'].str.split('/')

# Separa a lista criada pelo split em diferentes linhas para cada classe obtida
distribuicao_explodido_df = distribuicao_df.explode(column='CLASSE')

# Retorna a proporção de cada classe de ativo, separando as combinações
classe_sep = round(distribuicao_explodido_df.value_counts(subset='CLASSE', normalize=True).head(10) * 100, 2)
classe_sep

CLASSE
Herbicida                       29.92
Inseticida                      19.14
Fungicida                       18.54
Inseticida Microbiológico        8.51
Acaricida                        6.03
Fungicida microbiológico         3.83
Nematicida Microbiológico        2.74
Regulador de Crescimento         2.47
Agente Biológico de Controle     1.95
Acaricida Microbiológico         1.63
Name: proportion, dtype: float64

In [20]:
filt_bio_nao_sep = classe_nao_sep.index.str.contains('biológico', case=False)
bio_nao_sep = classe_nao_sep.iloc[filt_bio_nao_sep].sum()

filt_bio_sep = classe_sep.index.str.contains('biológico', case=False)
bio_sep = classe_sep.iloc[filt_bio_sep].sum()

display(Markdown(f'''\n

Ao analisar as diferentes classes dos ingredientes ativos, percebemos a predominância dos herbicidas, sendo aproximadamente **1 a cada 3** produtos um herbicida.

Quando separamos os produtos cujas classes abrangiam mais de um tipo de ação, vemos um **aumento** no número de inseticidas, significando que diversos produtos têm ação inseticida, mas também são classificados com outros tipos de ação.

Outro ponto a se destacar é a participação de produtos biológicos/microbiológicos, com **{bio_nao_sep}%** de participação na classificação das top 10 classes.
Quando separados, a proporção sobe para **{bio_sep}%**.

---'''))

Ao analisar as diferentes classes dos ingredientes ativos, percebemos a predominância dos herbicidas, sendo aproximadamente **1 a cada 3** produtos um herbicida.

Quando separamos os produtos cujas classes abrangiam mais de um tipo de ação, vemos um **aumento** no número de inseticidas, significando que diversos produtos têm ação inseticida, mas também são classificados com outros tipos de ação.

Outro ponto a se destacar é a participação de produtos biológicos/microbiológicos, com **17.66%** de participação na classificação das top 10 classes.
Quando separados, a proporção sobe para **18.66%**.

---

#### Número de produtos (micro)biológicos

In [21]:
# Resetando a variável
distribuicao_df = df[['NR_REGISTRO', 'CLASSE']].drop_duplicates('NR_REGISTRO')

e_biologico = distribuicao_df['CLASSE'].str.contains('biológico', case=False, na=False)
bio = distribuicao_df.loc[e_biologico].value_counts().sum()
bio

np.int64(795)

In [22]:
porc_bio = round(distribuicao_df.loc[e_biologico].value_counts().sum() / produtos_df['NR_REGISTRO'].value_counts().sum() * 100, 2)
porc_bio

np.float64(18.79)

In [23]:
display(Markdown(f'''\n

Ao todo, existem **{bio}** produtos cadastrados como (micro)biológicos, ou seja, **{porc_bio}%** dos produtos da base de dados são produtos (micro)biológicos.\n\n

---'''))

Ao todo, existem **795** produtos cadastrados como (micro)biológicos, ou seja, **18.79%** dos produtos da base de dados são produtos (micro)biológicos.



---

#### Principais empresas dententoras de produtos biológicos

In [24]:
# Seleciona colunas relevantes e remove duplicatas de produtos
biologico_df = df[['NR_REGISTRO', 'TITULAR', 'CLASSE']].drop_duplicates(subset=['NR_REGISTRO'])

# Cria uma coluna condicional onde se conter a palavra "biológico" na classe, ele retorne True
biologico_df['(MICRO)BIOLÓGICO'] = biologico_df['CLASSE'].str.contains('biológico', case=False, na=False)

# Cria uma variável com o agrupamento por titular de registro da coluna de (micro)biológicos
biologico = biologico_df.groupby('TITULAR', observed=True)['(MICRO)BIOLÓGICO'].sum()

# Mostra as 10 empresas com mais produtos (micro)biológicos cadastrados na base
maior_bio = biologico.nlargest(10) 
maior_bio

TITULAR
Koppert          48
Total            42
Simbiose         34
Vittia           25
Bioma            22
Ballagro         18
Biota            18
Solubio          18
Agrobiológica    17
Genica           17
Name: (MICRO)BIOLÓGICO, dtype: Int64

In [25]:
soma_bio = maior_bio.sum()
soma_bio

np.int64(259)

In [26]:
prop_bio = round(maior_bio.sum() / distribuicao_df.loc[e_biologico].value_counts().sum() * 100, 2)
prop_bio

np.float64(32.58)

In [27]:
filt_bio = maior_bio > 40
bio = maior_bio.loc[filt_bio].sum()


display(Markdown(f'''\n

Aqui vemos as 10 empresas com mais produtos (micro)biológicos cadastrados na base de dados.

Tanto a Koppert quanto a Biotrop (Total) possuem mais de **40** produtos com essa característica, totalizando **{bio}** produtos ao todo.

Quando somados os 10 maiores players no mercado de produtos (micro)biológicos, temos **{soma_bio}** produtos ao todo, ou ainda, **{prop_bio}%**, quase 1 a cada 3.

---'''))

Aqui vemos as 10 empresas com mais produtos (micro)biológicos cadastrados na base de dados.

Tanto a Koppert quanto a Biotrop (Total) possuem mais de **40** produtos com essa característica, totalizando **90** produtos ao todo.

Quando somados os 10 maiores players no mercado de produtos (micro)biológicos, temos **259** produtos ao todo, ou ainda, **32.58%**, quase 1 a cada 3.

---

#### Quais as principais empresas com produtos aprovados para a agricultura orgânica?

In [28]:
organico_df = df[['NR_REGISTRO', 'TITULAR', 'ORGANICOS']].drop_duplicates(subset='NR_REGISTRO')

organico_df['ORGANICO_SIM'] = organico_df['ORGANICOS'].str.contains('SIM', case=False, na=False)
organico_df['ORGANICO_NAO'] = organico_df['ORGANICOS'].str.contains('NAO', case=False, na=False)
organico_df['ORGANICO_OUTROS'] = organico_df['ORGANICOS'].str.contains('OUTROS', case=False, na=False)

orgs = organico_df.groupby('TITULAR')[['ORGANICO_SIM', 'ORGANICO_NAO', 'ORGANICO_OUTROS']].sum()
orgs.nlargest(n=10, columns='ORGANICO_SIM')

          ORGANICO_SIM  ORGANICO_NAO  ORGANICO_OUTROS
TITULAR
Koppert             15            36                0
Biota               14             4                0
Promip              13             1                0
TOPBIO              12             0                0
Bioma               10            12                0
Total               10            48                0
Vital               10             4                0
Coopavel             8             0                0
Genica               8             9                0
Noduagri             8             0                0

In [29]:
display(Markdown(f'''\n

Quando olhamos para as principais empresas detentoras de produtos aplicáveis à agricultura orgânica, vemos que há uma forte defasagem. A maioria se trata de produtos (micro/macro)biológicos utilizados nos tratamentos contra fungos, insetos e nematoides.

---'''))

Quando olhamos para as principais empresas detentoras de produtos aplicáveis à agricultura orgânica, vemos que há uma forte defasagem. A maioria se trata de produtos (micro/macro)biológicos utilizados nos tratamentos contra fungos, insetos e nematoides.

---

## Toxicologia e classe ambiental

Os agroquímicos no Brasil são classificados principalmente com base em sua **toxicidade para a saúde humana** e em seu **potencial de periculosidade ambiental**, conforme estabelecido pela Anvisa e regulamentado pelo Sistema Globalmente Harmonizado (GHS).

### Classificação Toxicológica (baseada em risco à saúde humana)
A classificação é indicada no rótulo por cores e categorias:

- **Categoria 1 – Produto Extremamente Tóxico** (faixa **vermelha**): produtos com DL50 oral em ratos ≤ 5 mg/kg (formulações sólidas) ou ≤ 20 mg/L (líquidas).
- **Categoria 2 – Produto Altamente Tóxico** (faixa **vermelha**): DL50 oral entre 5–50 mg/kg (sólidas) ou 20–200 mg/L (líquidas).
- **Categoria 3 – Produto Moderadamente Tóxico** (faixa **amarela**): DL50 oral entre 50–500 mg/kg (sólidas) ou 200–2.000 mg/L (líquidas).
- **Categoria 4 – Produto Pouco Tóxico** (faixa **azul**): DL50 oral > 500 mg/kg (sólidas) ou > 2.000 mg/L (líquidas).
- **Categoria 5 – Produto Improvável de Causar Dano Agudo** (faixa **azul**): produtos que não causam efeitos tóxicos agudos em doses normais.
- **Não classificado** (faixa **verde**): produtos cuja toxicidade não pôde ser definida ou que não foram avaliados.

> **Nota**: A reclassificação realizada pela Anvisa em 2019, com base no GHS, alterou a classificação de 1.924 produtos, com 43 enquadrados na Categoria 1 e 899 na Categoria 5.

---

### Quantos % dos produtos são categoria 1 (extremamente tóxico), 2, 3, 4 ou 5?

In [30]:
# Dicionário com o fim de padronizar as classificações toxicológicas dos produtos
mapa_toxico = {
    'Extremamente Tóxico': 'Categoria 1 - Extremamente Tóxico',
    'Categoria 1  Produto Extremamente Tóxico': 'Categoria 1 - Extremamente Tóxico',
    
    'Altamente Tóxico': 'Categoria 2 - Altamente Tóxico',
    'Categoria 2  Produto Altamente Tóxico': 'Categoria 2 - Altamente Tóxico',
    
    'Medianamente Tóxico': 'Categoria 3 - Moderadamente Tóxico',
    'Categoria 3  Produto Moderadamente Tóxico': 'Categoria 3 - Moderadamente Tóxico',
    
    'Pouco Tóxico': 'Categoria 4 - Pouco Tóxico',
    'Categoria 4  Produto Pouco Tóxico': 'Categoria 4 - Pouco Tóxico',
    
    'Categoria 5  Produto Improvável de Causar Dano Agudo': 'Categoria 5 - Improvável de Causar Dano',
    
    'Não Classificado - Produto Não Classificado': 'Não Classificado',
    'NÃO DETERMINADO DEVIDO À NATUREZA DO PRODUTO': 'Não Determinado',
    'BAIXA EXPOSIÇÃO PARA USO RESTRITO EM ARMADILHAS': 'Uso Restrito (Armadilhas)',
}

# Criação de coluna com a classificação padronizada
df['CLASSE_TOXICOLOGICA_PADRAO'] = df['CLASSE_TOXICOLOGICA'].map(mapa_toxico)

# Seleciona colunas relevantes e remove duplicatas de produtos
toxicidade_df = df[['NR_REGISTRO', 'CLASSE_TOXICOLOGICA_PADRAO']].drop_duplicates('NR_REGISTRO')

# Retorna a proporção de cada classificação no contexto geral da base de dados
prop_cat = round(toxicidade_df['CLASSE_TOXICOLOGICA_PADRAO'].value_counts(normalize=True) * 100, 2)
prop_cat

CLASSE_TOXICOLOGICA_PADRAO
Categoria 5 - Improvável de Causar Dano    52.61
Categoria 4 - Pouco Tóxico                 25.53
Não Classificado                           11.27
Categoria 3 - Moderadamente Tóxico          5.22
Categoria 2 - Altamente Tóxico              3.26
Categoria 1 - Extremamente Tóxico           1.13
Não Determinado                             0.90
Uso Restrito (Armadilhas)                   0.07
Name: proportion, dtype: float64

In [31]:
filt_pouco_toxico = prop_cat.index.str.contains('5') | prop_cat.index.str.contains('4')
prop_pouco_toxico = prop_cat.iloc[filt_pouco_toxico].sum()

filt_muito_toxico = prop_cat.index.str.contains('1') | prop_cat.index.str.contains('2')
prop_muito_toxico = prop_cat.iloc[filt_muito_toxico].sum()

display(Markdown(f'''\n

Podemos notar algo bastante positivo com essa tabela: **{prop_pouco_toxico:.2f}%** estão classificados ou como *improváveis de causar dano* ou como *pouco tóxicos*.

Apenas **{prop_muito_toxico:.2f}%** são classificados ou como *extremamente tóxicos* ou como *altamente tóxico*, significando uma baixa proporção frente ao universo do banco de dados.

---'''))

Podemos notar algo bastante positivo com essa tabela: **78.14%** estão classificados ou como *improváveis de causar dano* ou como *pouco tóxicos*.

Apenas **4.39%** são classificados ou como *extremamente tóxicos* ou como *altamente tóxico*, significando uma baixa proporção frente ao universo do banco de dados.

---

### Qual a distribuição toxicológica das classes de produtos?

In [32]:
# Seleciona colunas relevantes e remove duplicatas de produtos
classes_toxicologia_df = df[['NR_REGISTRO', 'CLASSE', 'CLASSE_TOXICOLOGICA_PADRAO']].drop_duplicates(subset=['NR_REGISTRO'])

# Cria colunas booleanas para as 5 classes toxicológicas
for x in range(1, 6):
    classes_toxicologia_df[f'CAT_{x}'] = classes_toxicologia_df['CLASSE_TOXICOLOGICA_PADRAO'].str.contains(f'Categoria {x}', case=False, na=False)

# Cria coluna booleana para a classe de "Não Classificado"
classes_toxicologia_df['NAO_CLAS'] = classes_toxicologia_df['CLASSE_TOXICOLOGICA_PADRAO'].str.contains('Não Classificado', case=False, na=False)

# Separa as classes em cada linha para melhor compreensão
classes_toxicologia_df['CLASSE'] = classes_toxicologia_df['CLASSE'].str.split('/')
classes_toxicologia = classes_toxicologia_df.explode(column='CLASSE')

# Agrupa por classe e soma a quantidade de produtos por classe
classes_toxicologia = classes_toxicologia.groupby('CLASSE', observed=True)[['CAT_1', 'CAT_2', 'CAT_3', 'CAT_4', 'CAT_5','NAO_CLAS']].sum()

# Adiciona coluna de total para facilitar ordenação
classes_toxicologia['TOTAL'] = classes_toxicologia.sum(axis=1)

# Ordena pelas classes com mais produtos e exibe as top 10
classes_toxicologia = classes_toxicologia.nlargest(n=10, columns='TOTAL')

classes_toxicologia

,CAT_1,CAT_2,CAT_3,CAT_4,CAT_5,NAO_CLAS,TOTAL
CLASSE,,,,,,,
Herbicida,6,20,28,419,894,63,1430
Inseticida,25,83,146,339,263,59,915
Fungicida,4,37,42,270,488,45,886
Inseticida Microbiológico,0,0,1,26,298,82,407
Acaricida,1,22,31,103,121,10,288
Fungicida microbiológico,0,0,1,1,140,41,183
Nematicida Microbiológico,0,0,0,0,84,47,131
Regulador de Crescimento,1,0,2,22,62,31,118
Acaricida Microbiológico,0,0,0,2,70,6,78
Agente Biológico de Controle,0,0,0,1,0,54,55

In [33]:
tot_ins = 0
for x in range(1,4):
    ins = classes_toxicologia.loc['Inseticida'][f'CAT_{x}']
    tot_ins += ins
tot_ins = tot_ins / classes_toxicologia.loc['Inseticida']['TOTAL'] * 100


display(Markdown(f'''\n

Herbicidas são os mais numerosos, mas também os menos tóxicos, onde a maioria deles registrados hoje são de **baixa toxicidade** (Categorias 4 e 5). Ou seja, apesar de representarem 1/3 dos produtos, herbicidas têm perfil toxicológico predominantemente baixo.

Inseticidas têm a **maior proporção de produtos nas categorias mais tóxicas** (1, 2 e 3) entre as classes principais, onde {tot_ins:.2f}% dos inseticidas registrados são classificados entre moderadamente a extremamente tóxicos. Isso se deve ao fato dos mecanismos de ação dos produtos atuarem por vias que são análogas nos seres humanos. 

Produtos microbiológicos são **extremamente seguros** com praticamente **zero** nas categorias tóxicas. Por exemplo, 100% dos nematicidas microbiológicos são classificados como baixa toxicidade ou não classificados.

Produtos biológicos frequentemente **não se enquadram** nas categorias toxicológicas tradicionais, o que faz sentido, já que são organismos vivos, não moléculas químicas.

Biológicos são **proporcionalmente muito mais seguros** que químicos. Menos de 1% dos produtos microbiológicos estão nas categorias de maior toxicidade, contra ~10-15% dos químicos.

Fungicidas são majoritariamente de baixa toxicidade, mas não tanto quanto herbicidas.

Reguladores de crescimento são predominantemente seguros ou não classificados.

---'''))

Herbicidas são os mais numerosos, mas também os menos tóxicos, onde a maioria deles registrados hoje são de **baixa toxicidade** (Categorias 4 e 5). Ou seja, apesar de representarem 1/3 dos produtos, herbicidas têm perfil toxicológico predominantemente baixo.

Inseticidas têm a **maior proporção de produtos nas categorias mais tóxicas** (1, 2 e 3) entre as classes principais, onde 27.76% dos inseticidas registrados são classificados entre moderadamente a extremamente tóxicos. Isso se deve ao fato dos mecanismos de ação dos produtos atuarem por vias que são análogas nos seres humanos.

Produtos microbiológicos são **extremamente seguros** com praticamente **zero** nas categorias tóxicas. Por exemplo, 100% dos nematicidas microbiológicos são classificados como baixa toxicidade ou não classificados.

Produtos biológicos frequentemente **não se enquadram** nas categorias toxicológicas tradicionais, o que faz sentido, já que são organismos vivos, não moléculas químicas.

Biológicos são **proporcionalmente muito mais seguros** que químicos. Menos de 1% dos produtos microbiológicos estão nas categorias de maior toxicidade, contra ~10-15% dos químicos.

Fungicidas são majoritariamente de baixa toxicidade, mas não tanto quanto herbicidas.

Reguladores de crescimento são predominantemente seguros ou não classificados.

---

### Classificação Ambiental (Potencial de Periculosidade Ambiental – PPA)
- **Classe I – Altamente Perigoso**
- **Classe II – Muito Perigoso**
- **Classe III – Perigoso**
- **Classe IV – Pouco Perigoso**

Essa classificação considera fatores como persistência no ambiente, bioacumulação e ecotoxicidade a organismos não-alvo.

In [34]:
ambiental_df = df[['NR_REGISTRO', 'CLASSE_AMBIENTAL']].drop_duplicates(subset='NR_REGISTRO')

tot_class_amb = round(ambiental_df['CLASSE_AMBIENTAL'].value_counts(normalize=True) * 100, 2)
tot_class_amb

CLASSE_AMBIENTAL
Produto Muito Perigoso ao Meio Ambiente        40.72
Produto Perigoso ao Meio Ambiente              32.52
Produto Pouco Perigoso ao Meio Ambiente        24.42
Produto Altamente Perigoso ao Meio Ambiente     2.13
Produto de Baixo Risco ao Meio Ambiente         0.21
Name: proportion, dtype: Float64

In [35]:
filt_pouco_perigoso = tot_class_amb.index.str.contains('Baixo', case=False) | tot_class_amb.index.str.contains('Pouco', case=False)
pouco_perigoso = tot_class_amb.iloc[filt_pouco_perigoso].sum()

filt_perigoso = tot_class_amb.index.str.contains('Altamente', case=False) | tot_class_amb.index.str.contains('Muito', case=False) | tot_class_amb.index.str.contains('produto perigoso', case=False)
perigoso = tot_class_amb.iloc[filt_perigoso].sum()

display(Markdown(f'''\n

Agora, quando damos um enfoque na classificação de dano ambiental dos produtos, temos uma imagem muito melhor sobre o potencial dano que existe ao manusear os produtos de maneira incorreta.

Apenas **{pouco_perigoso:.2f}%** são classificados como baixo risco ou pouco perigoso. **1/4!**\n
Enquanto isso, **{perigoso:.2f}%** dos produtos são considerados perigosos, muito perigosos ou altamente perigosos ao meio ambiente.

Para contextualizar, produtos nocivos ao meio ambiente geralmente se referem a produtos que tem alto potencial de deslocamento no solo, podendo atingir principalmente águas subterrâneas. Podem também se referir a produtos altamente persistentes no meio ambiente, produtos altamente tóxicos para organismos aquáticos ou ainda altamente tóxico para abelhas e outros insetos benéficos.

---'''))

Agora, quando damos um enfoque na classificação de dano ambiental dos produtos, temos uma imagem muito melhor sobre o potencial dano que existe ao manusear os produtos de maneira incorreta.

Apenas **24.63%** são classificados como baixo risco ou pouco perigoso. **1/4!**

Enquanto isso, **75.37%** dos produtos são considerados perigosos, muito perigosos ou altamente perigosos ao meio ambiente.

Para contextualizar, produtos nocivos ao meio ambiente geralmente se referem a produtos que tem alto potencial de deslocamento no solo, podendo atingir principalmente águas subterrâneas. Podem também se referir a produtos altamente persistentes no meio ambiente, produtos altamente tóxicos para organismos aquáticos ou ainda altamente tóxico para abelhas e outros insetos benéficos.

---

## Culturas alvo

#### Número de culturas na base de dados

In [36]:
culturas_df = df[['NR_REGISTRO','CULTURA']]
n_culturas = culturas_df['CULTURA'].nunique()
n_culturas

235

In [37]:
display(Markdown(f'''\n

Existem hoje **{n_culturas}** cadastradas no banco de dados.

---'''))

Existem hoje **235** cadastradas no banco de dados.

---

#### Quais culturas têm o maior número de produtos formulados autorizados (soja, milho, cana, algodão, citros etc.)?

In [38]:
culturas_df = df[['NR_REGISTRO','CULTURA']]
cultura = culturas_df.groupby('CULTURA')['NR_REGISTRO'].nunique()
cultura.nlargest(n=10)

CULTURA
Soja              2144
Algodão           1695
Milho             1624
Feijão            1336
Café              1216
Trigo             1166
Cana-de-açúcar    1156
Batata            1085
Citros            1079
Tomate            1071
Name: NR_REGISTRO, dtype: int64

In [39]:
display(Markdown(f'''\n

Na tabela acima, vemos a as 10 culturas agrícolas com maior número de produtos autorizados.\n

> **Os produtos podem atender mais de uma cultura.**

Isso significa que **um mesmo produto formulado** pode estar **associado a várias culturas** no sistema do AGROFIT.

Ou seja, o número de produtos listados **não equivale diretamente ao número total de produtos diferentes no sistema**, e sim ao número de **vínculos entre produtos e culturas**.

Por exemplo:

- Um produto registrado para Soja, Milho e Algodão contará **uma vez em cada uma dessas culturas**.
- Portanto, **o somatório das quantidades da tabela excede o número real de produtos únicos** cadastrados no banco.

As culturas líderes (como Soja, Algodão e Milho) refletem a **priorização comercial e técnica** do setor de defensivos no Brasil.\n
Porém, é importante considerar que os dados representam **vínculos de uso** e não produtos únicos, o que **limita comparações diretas** sem esse contexto.
'''))

Na tabela acima, vemos a as 10 culturas agrícolas com maior número de produtos autorizados.


> **Os produtos podem atender mais de uma cultura.**

Isso significa que **um mesmo produto formulado** pode estar **associado a várias culturas** no sistema do AGROFIT.

Ou seja, o número de produtos listados **não equivale diretamente ao número total de produtos diferentes no sistema**, e sim ao número de **vínculos entre produtos e culturas**.

Por exemplo:

- Um produto registrado para Soja, Milho e Algodão contará **uma vez em cada uma dessas culturas**.
- Portanto, **o somatório das quantidades da tabela excede o número real de produtos únicos** cadastrados no banco.

As culturas líderes (como Soja, Algodão e Milho) refletem a **priorização comercial e técnica** do setor de defensivos no Brasil.

Porém, é importante considerar que os dados representam **vínculos de uso** e não produtos únicos, o que **limita comparações diretas** sem esse contexto.

In [40]:
# Subconjunto com apenas as colunas relevantes
soja_df = df[['NR_REGISTRO', 'CULTURA']]

# Conta quantas culturas diferentes cada produto (NR_REGISTRO) possui
registros_com_1_cultura = soja_df.groupby('NR_REGISTRO', observed=True)['CULTURA'].nunique() == 1

# Pega somente os índices dos registros com uma única cultura
registros_so_uma_cultura = registros_com_1_cultura.loc[registros_com_1_cultura].index

# Filtra o dataframe original para manter apenas esses registros
so_1_cultura = soja_df['NR_REGISTRO'].isin(registros_so_uma_cultura)
apenas_uma_cultura_df = soja_df.loc[so_1_cultura]

# Filtra os que essa única cultura contém "Soja"
soja_masc = apenas_uma_cultura_df['CULTURA'].str.contains('Soja', case=True, na=False)
so_soja_df = apenas_uma_cultura_df.loc[soja_masc].drop_duplicates(subset='NR_REGISTRO')

so_soja = so_soja_df.value_counts().sum()

In [41]:
display(Markdown(f'''\n

E ao analisarmos somente os produtos **exclusivamente** utilizados na cultura da soja, temos hoje o número de **{so_soja}** produtos.

---'''))

E ao analisarmos somente os produtos **exclusivamente** utilizados na cultura da soja, temos hoje o número de **116** produtos.

---

### Quais os ingredientes ativos mais ofertados para a cultura da soja?

In [42]:
import re

# 1. Filtra Soja e seleciona colunas
df_soja = df[df['CULTURA'].str.contains('Soja|Todas as culturas', case=False, na=False)].copy()
df_soja = df_soja[['NR_REGISTRO', 'INGREDIENTE_ATIVO']]

# 2. Explode as misturas (quem tem '+')
df_soja['INGREDIENTE_ATIVO'] = df_soja['INGREDIENTE_ATIVO'].str.split('+')
df_exploded = df_soja.explode('INGREDIENTE_ATIVO')

# 3. Limpeza com Regex "Inteligente"
df_exploded['INGREDIENTE_LIMPO'] = df_exploded['INGREDIENTE_ATIVO'].str.strip()

# Remove concentrações (ex: "(200 g/L)")
df_exploded['INGREDIENTE_LIMPO'] = df_exploded['INGREDIENTE_LIMPO'].str.replace(r'\s*\(.*', '', regex=True)

# --- O PULO DO GATO DO 2,4-D ---
# Remove tudo após a vírgula, DESDE QUE não seja um número logo depois (Lookahead negativo)
# Isso mata ", isolado..." mas preserva "2,4-D"
df_exploded['INGREDIENTE_LIMPO'] = df_exploded['INGREDIENTE_LIMPO'].str.replace(r',(?!\d).*', '', regex=True)

# Remove Sais (ex: "- Sal de...", "Sal de...")
df_exploded['INGREDIENTE_LIMPO'] = df_exploded['INGREDIENTE_LIMPO'].str.replace(r'\s*-?\s*\bSal\b.*', '', regex=True, flags=re.IGNORECASE)

# Tira espaços extras
df_exploded['INGREDIENTE_LIMPO'] = df_exploded['INGREDIENTE_LIMPO'].str.strip()

# 4. Remove duplicatas dentro do mesmo produto e conta
df_unicos = df_exploded.drop_duplicates(subset=['NR_REGISTRO', 'INGREDIENTE_LIMPO'])
top_ingredientes = df_unicos['INGREDIENTE_LIMPO'].value_counts().head(10)

top_ingredientes

INGREDIENTE_LIMPO
glifosato                 166
Beauveria bassiana        156
Metarhizium anisopliae    139
Trichoderma harzianum      88
Azoxistrobina              85
tebuconazol                84
Glufosinato                77
mancozebe                  70
clorotalonil               67
Protioconazol              61
Name: count, dtype: int64

In [55]:
top_gli = top_ingredientes.index.get_loc(key='glifosato') + 1
glif = top_ingredientes.index.str.contains('glifosato', case=False)
glif = top_ingredientes.iloc[glif].sum()

top_beauveria = top_ingredientes.index.get_loc(key='Beauveria bassiana') + 1
beauveria = top_ingredientes.index.str.contains('Beauveria', case=False)
beauveria = top_ingredientes.iloc[beauveria].sum()

top_metarhizium = top_ingredientes.index.get_loc(key='Metarhizium anisopliae') + 1
metarhizium = top_ingredientes.index.str.contains('metarhizium', case=False)
metarhizium = top_ingredientes.iloc[metarhizium].sum()

top_trichoderma = top_ingredientes.index.get_loc(key='Trichoderma harzianum') + 1
trichoderma = top_ingredientes.index.str.contains('trichoderma', case=False)
trichoderma = top_ingredientes.iloc[trichoderma].sum()

azoxistrobina = top_ingredientes.index.str.contains('azoxistrobina', case=False)
azoxistrobina = top_ingredientes.iloc[azoxistrobina].sum()

tebuconazol = top_ingredientes.index.str.contains('tebuconazol', case=False)
tebuconazol = top_ingredientes.iloc[tebuconazol].sum()


display(Markdown(f'''\n

Os dados revelam que a agricultura brasileira vive um momento de transição. O tradicional herbicida químico **Glifosato** ocupa o **{top_gli}º** lugar com **{glif}** produtos registrados, confirmando que o controle de mato ainda é a prioridade básica nas lavouras.

Porém, a grande surpresa é a explosão dos Produtos Biológicos. Ocupando o {top_beauveria}º, {top_metarhizium}º e {top_trichoderma}º lugares com **Beauveria ({beauveria})**, **Metarhizium ({metarhizium})** e **Trichoderma ({trichoderma})**, eles mostram que o setor está investindo pesado em tecnologias mais sustentáveis para combater pragas.

O restante da lista é dominado por fungicidas (como **Azoxistrobina** com **{azoxistrobina}** e **Tebuconazol** com **{tebuconazol}**), essenciais para proteger a soja de doenças que podem destruir a plantação rapidamente.

---'''))

Os dados revelam que a agricultura brasileira vive um momento de transição. O tradicional herbicida químico **Glifosato** ocupa o **1º** lugar com **166** produtos registrados, confirmando que o controle de mato ainda é a prioridade básica nas lavouras.

Porém, a grande surpresa é a explosão dos Produtos Biológicos. Ocupando o 2º, 3º e 4º lugares com **Beauveria (156)**, **Metarhizium (139)** e **Trichoderma (88)**, eles mostram que o setor está investindo pesado em tecnologias mais sustentáveis para combater pragas.

O restante da lista é dominado por fungicidas (como **Azoxistrobina** com **85** e **Tebuconazol** com **84**), essenciais para proteger a soja de doenças que podem destruir a plantação rapidamente.

---

## Formulações e características técnicas

O que são formulações de agroquímicos

**Formulações de agroquímicos** são misturas preparadas industrialmente que combinam um **ingrediente ativo (i.a.)** — substância responsável pelo efeito fitossanitário (como controle de pragas, doenças ou plantas daninhas) — com **ingredientes inertes ou auxiliares** (como solventes, surfactantes, estabilizantes, corantes, etc.). Essa combinação é essencial para tornar o produto seguro, estável, eficaz e adequado para aplicação em campo.

A formulação tem como principais objetivos:
- **Aumentar a eficiência** do ingrediente ativo.
- **Facilitar o manuseio, armazenamento e aplicação** (por exemplo, em pulverizadores).
- **Melhorar a dispersão, adesão e penetração** do produto nas plantas ou no solo.
- **Reduzir riscos ao usuário e ao meio ambiente**, ao diluir ou encapsular o ingrediente ativo em sua forma pura, que pode ser altamente tóxico.

As formulações podem ser **líquidas** (como concentrados emulsionáveis – EC, suspensões concentradas – SC, concentrado solúvel – SL) ou **sólidas** (como pós molháveis – WP, grânulos dispersíveis em água – WG), e são escolhidas com base no tipo de agroquímico, alvo de aplicação, método de aplicação e condições ambientais.

> **Importante**: O rótulo do produto indica a **formulação**, o **ingrediente ativo**, a **concentração (i.a.)** e, em alguns casos, o **equivalente ácido (e.a.)**, que é fundamental para comparar eficiência entre produtos.

### Quais são os tipos de formulação mais comuns (SL, WG, SC, EC, WP etc.)?

In [62]:
formulacoes_df = df[['NR_REGISTRO', 'FORMULACAO']].drop_duplicates(subset='NR_REGISTRO')
formulacoes_df = round(formulacoes_df.value_counts(subset='FORMULACAO', normalize=True) * 100, 2).head(10)
formulacoes_df

FORMULACAO
SC - Suspensão Concentrada                      28.41
EC - Concentrado Emulsionável                   16.53
WG - Grânulos Dispersíveis em Água              15.00
SL - Concentrado Solúvel                        12.89
WP - Pó Molhável                                 9.91
FS - Suspensão Concentrada p/ Trat. Sementes     2.86
SP - Pó Solúvel                                  1.68
Insetos Vivos                                    1.42
OD - Dispersão de Óleo                           1.40
SG - Granulado Solúvel                           1.25
Name: proportion, dtype: float64

In [65]:
SC = formulacoes_df.index.str.contains('SC - Suspensão Concentrada', case=False)
SC = formulacoes_df.iloc[SC].sum()

EC = formulacoes_df.index.str.contains('EC - Concentrado Emulsionável', case=False)
EC = formulacoes_df.iloc[EC].sum()

SL = formulacoes_df.index.str.contains('SL - Concentrado Solúvel', case=False)
SL = formulacoes_df.iloc[SL].sum()

WP = formulacoes_df.index.str.contains('WP - Pó Molhável', case=False)
WP = formulacoes_df.iloc[WP].sum()

top_WG = formulacoes_df.index.get_loc(key='WG - Grânulos Dispersíveis em Água') + 1
WG = formulacoes_df.index.str.contains('WG', case=False)
WG = formulacoes_df.iloc[WG].sum()

insetos = formulacoes_df.index.str.contains('Insetos Vivos', case=False)
insetos = formulacoes_df.iloc[insetos].sum()


display(Markdown(f'''\n

Os dados indicam uma clara preferência do mercado por produtos que facilitam a vida do agricultor na hora de preparar a calda para aplicação.

1.  A liderança absoluta da **Suspensão Concentrada (SC)**, com **{SC}%**, junto com o **Concentrado Emulsionável (EC)** (**{EC}%**) e o **Solúvel (SL)** (**{SL}%**), mostra que a maioria esmagadora dos produtos é líquida. Isso ocorre pela facilidade de medir e despejar o produto no tanque, evitando erros e perda de tempo.
2.  Vemos uma evolução importante nos produtos sólidos. O pó que sempre levanta poeira (**WP - Pó Molhável**, com **{WP}%**) está perdendo espaço para o moderno **WG (Grânulos Dispersíveis)**, que já ocupa o {top_WG}º lugar com **{WG}%**. O WG é mais seguro para quem aplica, pois não gera poeira tóxica ao ser manuseado, além de diluir mais fácil na água.
3.  A presença de **"Insetos Vivos" ({insetos}%)** no ranking, embora pequena, marca a entrada oficial das vespas (mencionadas anteriormente) e predadores naturais como produtos comerciais de prateleira.

Em resumo, a indústria tem focado em criar produtos que sejam, ao mesmo tempo, mais fáceis de misturar e mais seguros para o trabalhador rural.

---'''))

Os dados indicam uma clara preferência do mercado por produtos que facilitam a vida do agricultor na hora de preparar a calda para aplicação.

1.  A liderança absoluta da **Suspensão Concentrada (SC)**, com **28.41%**, junto com o **Concentrado Emulsionável (EC)** (**16.53%**) e o **Solúvel (SL)** (**12.89%**), mostra que a maioria esmagadora dos produtos é líquida. Isso ocorre pela facilidade de medir e despejar o produto no tanque, evitando erros e perda de tempo.
2.  Vemos uma evolução importante nos produtos sólidos. O pó que sempre levanta poeira (**WP - Pó Molhável**, com **9.91%**) está perdendo espaço para o moderno **WG (Grânulos Dispersíveis)**, que já ocupa o 3º lugar com **15.0%**. O WG é mais seguro para quem aplica, pois não gera poeira tóxica ao ser manuseado, além de diluir mais fácil na água.
3.  A presença de **"Insetos Vivos" (1.42%)** no ranking, embora pequena, marca a entrada oficial das vespas (mencionadas anteriormente) e predadores naturais como produtos comerciais de prateleira.

Em resumo, a indústria tem focado em criar produtos que sejam, ao mesmo tempo, mais fáceis de misturar e mais seguros para o trabalhador rural.

---